version: '3.9'

services:
  springboot_container:
    build: .

    restart: always

    environment:
      DB_URL: "${DOCKER_DB_URL}"
      DB_NAME: "${DB_NAME}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      BUCKET_NAME: "${BUCKET_NAME}"
      SERVER_URL: "${SERVER_URL}"

    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
